development: 
  adapter: postgresql
  encoding: utf8
  database: geotagging_development
  pool: 5

test: 
  adapter: postgresql 
  encoding: utf8 
  reconnect: false 
  database: geotagging_test
  pool: 5