# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_map_api_key: <%= ENV["GOOGLE_MAP_API_KEY"] %>

  admin_name: Admin.Qulix
  admin_email: admin@qulix.com
  admin_password: 12345678

test:
  secret_key_base: cd16602b2a3d44fe995a0b0aacc0570c68cbff0abe14a33095d1a1a043919022a8f81322ddc745fce26449e681060017c23feb86229fadac161692a2128d1310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_map_api_key: <%= ENV["GOOGLE_MAP_API_KEY"] %>
